# Generated by Django 5.1.6 on 2025-02-20 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('num_serie', models.CharField(max_length=50, unique=True, verbose_name='Número de serie')),
                ('fecha_adquisicion', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vida_util', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('B', 'Baja'), ('R', 'Reparación')], default='A', max_length=1)),
                ('etiquetas', models.ManyToManyField(to='activos.etiqueta')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activos.ubicacion')),
            ],
        ),
    ]
