# Generated by Django 5.1.6 on 2025-02-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='activos_fotos'),
        ),
    ]
